[package]
name = "c5store"
version = "0.2.7"
authors = ["Norm O <normo.pub@gmail.com>"]
edition = "2021"
description = "Provides a unified store for configuration and secrets."
license = "MPL-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "^0.22"
curve25519-parser = { version = "^0" }
ecies_25519 = { version = "^0" }
log = "^0.4"
maplit = "^1"
multimap = "^0.10"
natord = "^1.0"
num-rational = "^0.4"
num-traits = "^0.2"
parking_lot = "^0.12"
paste = "^1"
scheduled-thread-pool = "^0.2"
serde = { version = "^1", features = ["derive"] }
serde_json = "^1"
serde_yaml = "^0"
sha2 = "^0.10"
shellexpand = "^3.0"
skiplist = "^0.5"

[dev-dependencies]
serde_test = "^1.0"